### ISSUE TITLE
pr-preview-detect failing consistently

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt.live#30]
See https://github.com/web-platform-tests/wpt/actions?query=workflow%3Apr-preview-detect; pr-preview-detect is failing for most PRs.

Error is in the `Detect deployment` step:

```
INFO:__main__:Waiting up to 600 seconds for Deployment wpt-preview-24317 to be available on https://wptpr.live
INFO:__main__:Issuing request: GET https://api.github.com/rate_limit
INFO:__main__:Response status code: 200
INFO:__main__:Limit for "core" resource: 4961/5000
INFO:__main__:Issuing request: POST https://api.github.com/repos/web-platform-tests/wpt/deployments/242378550/statuses
INFO:__main__:Response status code: 201
Traceback (most recent call last):
  File "./tools/ci/pr_preview.py", line 431, in <module>
    values.pop('func')(**values)
  File "./tools/ci/pr_preview.py", line 372, in detect
    while not is_deployed(target, deployment):
  File "./tools/ci/pr_preview.py", line 284, in is_deployed
    '{}/.git/worktrees/{}/HEAD'.format(host, worktree_name)
  File "/home/runner/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/runner/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/runner/.local/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/runner/.local/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/runner/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='wptpr.live', port=443): Max retries exceeded with url: /.git/worktrees/24317/HEAD (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe699b68a90>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by stephenmcgruer** [comment]
This looks like we're unable to reach wptpr.live on HTTPS. Trying https://wptpr.live/.git/worktrees/24317/HEAD on my browser appears to work, going to see if the logs have any errors now.

**Comment by stephenmcgruer** [comment]
This started failing around:

```
wpt-preview-24221 pr-preview-detect #819: Deployment to wpt-preview-24221 by wpt-pr-bot
8 days ago 3m 5s
```

Run wpt-preview-24220 and earlier worked fine.

**Comment by stephenmcgruer** [comment]
We're OOMing regularly in the logs:

```
A 2020-06-25T09:57:22.729902Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T09:57:29.005720Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:09:22.007536Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:14:55.012702Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:23:44.948028Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:32:20.376228Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:33:25.883778Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:37:23.476688Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:45:14.734220Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:49:37.139600Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:53:09.300408Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:53:55.017769Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:57:08.853442Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T10:58:12.896398Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T11:19:41.991720Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T11:52:19.568589Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T12:04:28.583051Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T12:12:22.737367Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T12:20:17.298379Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T12:36:02.357910Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T12:40:51.266332Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T12:44:07.773423Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T12:45:18.567715Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T13:20:02.741232Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T13:20:38.804147Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
A 2020-06-25T13:28:02.450472Z containerd invoked oom-killer: gfp_mask=0x6200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=-999 
```

**Comment by Hexcles** [comment]
This happened before: https://github.com/web-platform-tests/wpt.live/commit/4e24f6c8fa5b244ed40afa44bd0dd0ca396e6620

We suspect `git gc` is using too much memory (~1GB).

**Comment by stephenmcgruer** [comment]
The upgrade appears to have resolved things. Actions are succeeding, and we see no ooms in the logs since the switchover that I can see.
